### ISSUE TITLE
FFI Error when following Metacello install instructions

### ISSUE THREAD

**Issue by darth-cheney** [tom95/sqFreeTypeFont#1]
Hi,

I'm getting the following error -- which I think is FFI related -- when attempting to install via the Metacello instructions in the readme:
```
Error: ExternalAddress called #basicNew: with invalid argument nil
```
  
I'm running Pop_os 20.04 (Ubuntu-derives), Squeak 5.3. I *did* install the FFI already via the startup preferences wizard, perhaps that's the issue?
  
Screenshot of stack:
![FreeTypeError](https://user-images.githubusercontent.com/1640299/89414496-7ddb9f00-d6f8-11ea-81e5-190cc80dd52f.png)

**Comment by tom95** [comment]
Hey, would it be possible for you to work in a Squeak-trunk image instead? I'm making use of some of the niceties that Marcel added in FFI recently, but with that he also upgraded other calls to be up-to-date with trunk, so for example you'll likely also run into errors with `beWritableObject` missing later on.

If not, I can have a quick check for how complicated it might be to support older versions, too.

**Comment by darth-cheney** [comment]
Ok I've tried using the latest Trunk image.
  
First I got the following warning:
![Warning](https://user-images.githubusercontent.com/1640299/89417080-348d4e80-d6fc-11ea-87e7-9f31b630ee05.png)
 
I proceeded and the rest of the install seemed to go fine. But when I tried the TextMorph example with the font loading I got:
![Error: External module not found](https://user-images.githubusercontent.com/1640299/89417119-42db6a80-d6fc-11ea-97b7-400ec3876597.png)
  
I assume this means it cannot find the freetype module for some reason. I'm not 100% sure I have it installed (I assumed that freetype is what Ubuntu uses, but maybe that's wrong?) Perhaps I need to install a dev version to get the shared library?

**Comment by tom95** [comment]
Squeak's module lookup is a little quirky for the arch-specific libraries. Could you try starting your squeak with `env LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/" ./squeak.sh` and see if that works?

**Comment by darth-cheney** [comment]
Ok excellent that has worked and the font can load without error.
  
Unfortunately this appears to have some of the same glyph lookup problems as the standard TTFont classes, when it comes to the fonts that I am using (they can be [found here](https://www.hethport.uni-wuerzburg.de/cuneifont/), in particular the one called Assurbanipal).
  
When I have time next I might dig into this library and see what's happening. As I mentioned on the mailing list, I think I have some idea of what's going on in the standard TTF package, but I'm having a hard time wrapping my head around the potential solution.
  
The package loads and runs though, so def feel free to close this issue.

**Comment by tom95** [comment]
Thank you for reporting back, I will update the README accordingly!

Some pointers for your continued investigation:
- we also created a project that is calling into Pango (the text stack on ubuntu/gnome) for its text rendering because we needed support for complex scripts such as Arabic: https://github.com/tom95/Pheno#pango Note that Pheno can integrate with Morphic but is not necessarily built to do so. For an easy way to hack a different font into Pheno, you could edit `PHPangoTextLayout>>primLayout:font:` and put the name string of the font as installed in your system.
- the likely problem given that it doesn't work with freetype is that you need advanced shaping rules as defined by harzbuff. If it does turn out to work using Pango, this is a likely (but not the only) explanation. Both integrating Harfbuzz and an implementation of the advanced OpenType rules you mentioned in squeak's TTFonts would be of tremendous benefit for Squeak. If you were to start investigating a Harzbuff integration I could provide some more ideas.

I'll close this issue as such now, if you have follow up questions, please feel free to "abuse" this issue to continue the discussion (unless it's specifically Pheno-related of course, then we can move to its issue tracker) :)
